# Generated by Django 5.2 on 2026-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_job_salary_job_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
