# Generated by Django 5.2 on 2026-03-22 19:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_rename_timestamp_job_updated_at_job_created_at_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='bookmarkjob',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bookmarkjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmarkjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkjob',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'location'], name='jobapp_job_title_e702a8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_published', 'is_closed'], name='jobapp_job_is_publ_b62738_idx'),
        ),
    ]
