# Generated by Django 5.2 on 2026-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_rename_timestamp_applicant_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('0', 'Entry Level'), ('1', 'Mid Level'), ('2', 'Senior Level'), ('3', 'Lead / Manager')], default='entry', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('1', 'Remote'), ('2', 'Hybrid'), ('3', 'On-site')], default='onsite', max_length=10),
        ),
    ]
