# Generated by Django 5.2 on 2026-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_job_experience_level_alter_job_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('0', 'Entry Level'), ('1', 'Mid Level'), ('2', 'Senior Level'), ('3', 'Lead / Manager')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('1', 'Remote'), ('2', 'Hybrid'), ('3', 'On-site')], default='3', max_length=1),
        ),
    ]
