# Generated by Django 3.0 on 2020-04-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='catagory',
            new_name='category',
        ),
    ]
